from fpdf import FPDF
import os

BASE = r"C:\Users\srush\Downloads\enterprise-rag-chatbot\enterprise-rag-chatbot\data"
COMPANY = "TechCorp Enterprises Pvt. Ltd."


class Doc(FPDF):
    def __init__(self, doc_title):
        super().__init__()
        self.doc_title = doc_title
        self.set_margins(22, 22, 22)
        self.set_auto_page_break(True, 22)

    def header(self):
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(99, 102, 241)
        self.cell(0, 7, COMPANY, new_x="LMARGIN", new_y="NEXT")
        self.set_font("Helvetica", "", 8)
        self.set_text_color(148, 163, 184)
        self.cell(0, 5, self.doc_title, new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(226, 232, 240)
        self.line(22, self.get_y(), 188, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-14)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(148, 163, 184)
        self.cell(0, 6, f"Page {self.page_no()}  |  Confidential  |  {COMPANY}", align="C")

    def cover(self, title, subtitle, dept, effective, version, approved):
        self.add_page()
        self.ln(18)
        self.set_font("Helvetica", "B", 26)
        self.set_text_color(30, 41, 59)
        self.multi_cell(0, 12, title, align="C")
        self.ln(4)
        self.set_font("Helvetica", "", 13)
        self.set_text_color(100, 116, 139)
        self.multi_cell(0, 7, subtitle, align="C")
        self.ln(10)
        self.set_draw_color(99, 102, 241)
        self.set_line_width(0.8)
        self.line(55, self.get_y(), 155, self.get_y())
        self.set_line_width(0.2)
        self.ln(12)
        for label, val in [
            ("Department", dept),
            ("Effective Date", effective),
            ("Version", version),
            ("Approved By", approved),
            ("Classification", "Internal - Confidential"),
        ]:
            self.set_font("Helvetica", "B", 10)
            self.set_text_color(99, 102, 241)
            self.cell(50, 8, label + ":")
            self.set_font("Helvetica", "", 10)
            self.set_text_color(30, 41, 59)
            self.cell(0, 8, val, new_x="LMARGIN", new_y="NEXT")

    def h1(self, text):
        self.ln(5)
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(99, 102, 241)
        self.cell(0, 9, text, new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(199, 210, 254)
        self.line(22, self.get_y(), 188, self.get_y())
        self.ln(3)

    def h2(self, text):
        self.ln(3)
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(30, 41, 59)
        self.cell(0, 7, text, new_x="LMARGIN", new_y="NEXT")
        self.ln(1)

    def _clean(self, text):
        return text.replace("—", "-").replace("–", "-").replace("’", "'").replace("‘", "'").replace("“", '"').replace("”", '"')

    def body(self, text):
        self.set_x(22)
        self.set_font("Helvetica", "", 10)
        self.set_text_color(51, 65, 85)
        self.multi_cell(0, 6, self._clean(text), new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

    def bullet(self, text):
        self.set_font("Helvetica", "", 10)
        self.set_text_color(51, 65, 85)
        self.set_x(28)
        self.cell(6, 6, "-")
        self.multi_cell(0, 6, self._clean(text), new_x="LMARGIN", new_y="NEXT")

    def trow(self, c1, c2, fill=False):
        if fill:
            self.set_fill_color(239, 246, 255)
        self.set_font("Helvetica", "B" if fill else "", 10)
        self.set_text_color(30, 41, 59)
        self.cell(65, 8, self._clean(c1), border=1, fill=fill)
        self.set_font("Helvetica", "", 10)
        self.cell(101, 8, self._clean(c2), border=1, fill=False, new_x="LMARGIN", new_y="NEXT")

    def new(self):
        self.add_page()


def save(pdf, folder, filename):
    path = os.path.join(BASE, folder)
    os.makedirs(path, exist_ok=True)
    pdf.output(os.path.join(path, filename))
    print(f"  Created: {folder}/{filename}")


def make_attendance():
    p = Doc("Attendance Policy")
    p.cover("Employee Attendance Policy",
            "Guidelines for Work Attendance, Punctuality & Absence Management",
            "Human Resources", "January 1, 2025", "v2.1", "Chief Human Resources Officer")
    p.new()
    p.h1("1. Purpose & Scope")
    p.body("This policy defines attendance expectations for all employees of TechCorp Enterprises. Consistent attendance is vital to team productivity and client commitments. This policy applies company-wide across all departments.")
    p.h1("2. Standard Working Hours")
    p.h2("2.1 Core Hours")
    p.body("All employees must be available during core hours: 10:00 AM to 4:00 PM, Monday through Friday.")
    p.h2("2.2 Full Working Day")
    p.body("A standard working day is 8 hours including a 30-minute lunch break, typically 9:00 AM to 6:00 PM. Flexible start times between 8:00 AM and 10:30 AM are permitted with manager approval.")
    p.h2("2.3 Attendance Recording")
    p.body("Attendance must be recorded via the HRMS portal daily. Failure to mark attendance is treated as absent unless corrected within 24 hours.")
    p.h1("3. Punctuality Standards")
    p.body("Late arrivals are categorised as follows:")
    p.bullet("Minor Late (under 15 min): No penalty for the first 3 occurrences per quarter.")
    p.bullet("Significant Late (15 to 60 min): Counted as half-day absent after 3 occurrences.")
    p.bullet("Major Late (over 60 min): Counted as full-day absent unless prior approval was given.")
    p.h1("4. Absence Notification")
    p.body("Employees unable to attend must:")
    p.bullet("Notify their manager before 9:30 AM on the day of absence.")
    p.bullet("Submit an absence request on HRMS within 24 hours.")
    p.bullet("Provide medical documentation for absences exceeding 2 consecutive days.")
    p.bullet("Obtain manager approval for planned absences at least 48 hours in advance.")
    p.h1("5. Attendance Categories")
    p.trow("Category", "Description", fill=True)
    p.trow("Present", "Employee worked full scheduled hours")
    p.trow("Absent (Approved)", "Pre-approved absence with valid reason")
    p.trow("Absent (Unapproved)", "Absence without notification or approval")
    p.trow("Half Day", "Employee worked 4 or fewer hours")
    p.trow("Work From Home", "Remote work with prior approval")
    p.trow("On Duty", "Official travel or off-site assignment")
    p.h1("6. Excessive Absenteeism")
    p.body("More than 3 unapproved absences per quarter will result in:")
    p.bullet("1st occurrence: Verbal warning from manager.")
    p.bullet("2nd occurrence: Written warning from HR.")
    p.bullet("3rd occurrence: Performance Improvement Plan initiated.")
    p.bullet("4th occurrence: Disciplinary action up to termination.")
    p.h1("7. Public Holidays")
    p.body("TechCorp observes all national public holidays. A holiday calendar is shared at the start of each year. Employees working on public holidays receive compensatory leave.")
    save(p, "employee", "Attendance_Policy.pdf")


def make_leave():
    p = Doc("Leave Policy")
    p.cover("Employee Leave Policy",
            "Comprehensive Leave Entitlements, Application & Approval Guidelines",
            "Human Resources", "January 1, 2025", "v3.0", "Chief Human Resources Officer")
    p.new()
    p.h1("1. Purpose")
    p.body("TechCorp Enterprises is committed to employee well-being and work-life balance. This policy outlines leave entitlements, application procedures, and conditions of approval.")
    p.h1("2. Leave Entitlements")
    p.trow("Leave Type", "Entitlement Per Year", fill=True)
    p.trow("Annual Leave (Privilege Leave)", "20 working days")
    p.trow("Sick Leave", "12 working days")
    p.trow("Casual Leave", "8 working days")
    p.trow("Maternity Leave", "26 weeks (as per law)")
    p.trow("Paternity Leave", "10 working days")
    p.trow("Bereavement Leave", "5 working days")
    p.trow("Emergency Leave", "3 working days")
    p.trow("Compensatory Off", "As earned")
    p.h1("3. Annual Leave")
    p.body("Annual Leave allows employees rest and personal time.")
    p.bullet("Employees earn 1.66 days of Annual Leave per month worked.")
    p.bullet("Up to 10 days can be carried forward to the next calendar year.")
    p.bullet("Encashment of up to 10 unused days is permitted at year-end or resignation.")
    p.bullet("Annual Leave must be applied at least 5 working days in advance.")
    p.bullet("Maximum 15 consecutive days can be taken at one time.")
    p.h1("4. Sick Leave")
    p.body("Sick Leave is granted when an employee cannot work due to illness.")
    p.bullet("Notify manager on the same morning as the absence.")
    p.bullet("Medical certificate required for sick leave exceeding 2 consecutive days.")
    p.bullet("Sick leave does not carry forward or get encashed.")
    p.bullet("Employees on probation are entitled to 6 sick leave days.")
    p.h1("5. Casual Leave")
    p.bullet("Maximum 2 consecutive casual leave days allowed.")
    p.bullet("Cannot be combined with other leave types.")
    p.bullet("Cannot be carried forward or encashed.")
    p.bullet("Requires same-day or advance notification to manager.")
    p.h1("6. Maternity Leave")
    p.bullet("26 weeks of paid maternity leave for the first two children.")
    p.bullet("12 weeks for the third child onwards.")
    p.bullet("Adoptive mothers of children under 3 months receive 12 weeks.")
    p.bullet("Employees must inform HR at least 8 weeks before expected delivery.")
    p.h1("7. Leave Application Process")
    p.bullet("Step 1: Log in to HRMS portal and navigate to Leave Management.")
    p.bullet("Step 2: Select leave type, dates, and provide reason.")
    p.bullet("Step 3: Submit for manager approval.")
    p.bullet("Step 4: HR confirms approved leave via email.")
    p.body("Unapproved leave is treated as Loss of Pay (LOP).")
    save(p, "employee", "Leave_Policy.pdf")


def make_conduct():
    p = Doc("Code of Conduct")
    p.cover("Employee Code of Conduct",
            "Standards of Professional Behaviour, Ethics & Workplace Integrity",
            "Human Resources & Legal", "January 1, 2025", "v4.0", "CEO & Chief HR Officer")
    p.new()
    p.h1("1. Introduction")
    p.body("TechCorp Enterprises is committed to a workplace built on integrity, respect, and professionalism. This Code sets standards expected from every employee, contractor, and intern. Violations may result in disciplinary action including termination.")
    p.h1("2. Professional Conduct")
    p.h2("2.1 Workplace Behaviour")
    p.bullet("Treat all colleagues, clients, and stakeholders with courtesy and respect.")
    p.bullet("Maintain a professional demeanour in all work-related communications.")
    p.bullet("Arrive on time, meet deadlines, and fulfil responsibilities diligently.")
    p.h2("2.2 Communication Standards")
    p.bullet("Use professional language in emails, meetings, and written communications.")
    p.bullet("Avoid sending offensive, discriminatory, or inappropriate content.")
    p.bullet("Confidential information must not be shared without authorisation.")
    p.h1("3. Anti-Harassment & Discrimination")
    p.body("TechCorp maintains a zero-tolerance policy on harassment and discrimination, including:")
    p.bullet("Sexual harassment — verbal, physical, or visual.")
    p.bullet("Discrimination based on gender, age, religion, caste, nationality, or disability.")
    p.bullet("Bullying, intimidation, or any form of workplace violence.")
    p.body("Employees must report harassment to HR immediately. All complaints are treated confidentially.")
    p.h1("4. Conflict of Interest")
    p.bullet("Disclose any outside employment, investments, or business relationships to HR.")
    p.bullet("Do not accept gifts or benefits exceeding INR 2,000 from vendors or clients.")
    p.bullet("Do not engage in any business activity that competes with TechCorp.")
    p.h1("5. Confidentiality & Data Protection")
    p.bullet("Never share proprietary information, trade secrets, or client data with unauthorised parties.")
    p.bullet("Use company systems and data only for legitimate business purposes.")
    p.bullet("Lock computer screens when stepping away from workstations.")
    p.body("Confidentiality obligations continue for 2 years after the cessation of employment.")
    p.h1("6. Social Media Policy")
    p.bullet("Do not post confidential company information or client details on social media.")
    p.bullet("Do not make disparaging remarks about TechCorp or its employees online.")
    p.bullet("Obtain Marketing approval before posting on behalf of TechCorp.")
    p.h1("7. Disciplinary Procedures")
    p.trow("Severity", "Action Taken", fill=True)
    p.trow("Minor Violation", "Verbal warning and counselling")
    p.trow("Repeated Minor Violation", "Written warning on record")
    p.trow("Moderate Violation", "Final written warning or suspension without pay")
    p.trow("Serious Violation", "Immediate termination of employment")
    save(p, "employee", "Code_of_Conduct.pdf")


def make_wfh():
    p = Doc("Work From Home Policy")
    p.cover("Work From Home (WFH) Policy",
            "Remote Work Guidelines, Eligibility & Productivity Expectations",
            "Human Resources & IT", "January 1, 2025", "v2.3", "Chief Operating Officer")
    p.new()
    p.h1("1. Purpose")
    p.body("This policy provides guidelines for employees working remotely. TechCorp supports flexible work while ensuring productivity, security, and collaboration standards are maintained.")
    p.h1("2. Eligibility")
    p.bullet("Confirmed employee who has completed probation of 6 months.")
    p.bullet("Role suitable for remote work as determined by department head.")
    p.bullet("Performance rating of Meets Expectations or above in last review.")
    p.bullet("No active Performance Improvement Plan.")
    p.bullet("Reliable internet connection and a dedicated workspace at home.")
    p.h1("3. WFH Arrangements")
    p.trow("WFH Type", "Description", fill=True)
    p.trow("Regular WFH", "Up to 2 days per week with manager approval")
    p.trow("Occasional WFH", "Ad-hoc, approved at least 24 hours in advance")
    p.trow("Full Remote", "Exceptional cases, approved by HR and Director")
    p.trow("Emergency WFH", "During extreme weather or public health emergencies")
    p.h1("4. Working Hours & Availability")
    p.bullet("Maintain regular hours of 9:00 AM to 6:00 PM while working from home.")
    p.bullet("Be reachable on all company communication tools at all times.")
    p.bullet("Attend all scheduled meetings with camera on unless explicitly waived.")
    p.bullet("Update availability status on the HRMS portal each WFH day.")
    p.h1("5. Equipment & Technology")
    p.body("TechCorp provides: laptop, VPN access, and collaboration software licences.")
    p.body("Employees are responsible for:")
    p.bullet("Maintaining a stable internet connection of at least 10 Mbps.")
    p.bullet("Keeping the home workspace ergonomic and free from distractions.")
    p.bullet("Ensuring company devices are not used by family members.")
    p.h1("6. Security Requirements")
    p.bullet("Use company-issued VPN when accessing all internal systems.")
    p.bullet("Never use public Wi-Fi for work without VPN.")
    p.bullet("Lock screen when stepping away from the workstation.")
    p.bullet("Report any security incidents or lost devices to IT within 1 hour.")
    p.h1("7. Productivity Expectations")
    p.bullet("Daily stand-up attendance is mandatory.")
    p.bullet("Task updates must be logged in the project management tool daily.")
    p.bullet("Response time to messages must not exceed 30 minutes during working hours.")
    p.bullet("WFH privileges may be revoked for repeated productivity issues.")
    save(p, "employee", "Work_From_Home_Policy.pdf")


def make_payroll():
    p = Doc("Payroll Policy")
    p.cover("Payroll Policy",
            "Compensation Structure, Pay Schedule & Deductions Guidelines",
            "Finance & Human Resources", "January 1, 2025", "v2.0",
            "Chief Financial Officer & CHRO")
    p.new()
    p.h1("1. Purpose & Scope")
    p.body("This policy governs payroll processes at TechCorp Enterprises, ensuring employees are compensated accurately and on time. It covers all full-time, part-time, and contractual employees.")
    p.h1("2. Pay Schedule")
    p.trow("Pay Element", "Details", fill=True)
    p.trow("Pay Frequency", "Monthly")
    p.trow("Pay Date", "Last working day of each month")
    p.trow("Payment Method", "Direct bank transfer (NEFT/IMPS)")
    p.trow("Payslip Availability", "HRMS portal by 25th of each month")
    p.trow("Salary Revision Cycle", "Annual (April) or on promotion")
    p.h1("3. Compensation Structure")
    p.trow("Component", "Percentage of CTC", fill=True)
    p.trow("Basic Salary", "40%")
    p.trow("House Rent Allowance (HRA)", "20%")
    p.trow("Special Allowance", "20%")
    p.trow("Performance Bonus", "10%")
    p.trow("Provident Fund Contribution", "5%")
    p.trow("Medical Allowance", "3%")
    p.trow("Other Benefits", "2%")
    p.h1("4. Statutory Deductions")
    p.bullet("Provident Fund (PF): 12% of Basic Salary as employee contribution.")
    p.bullet("Professional Tax (PT): As per state government regulations.")
    p.bullet("Income Tax (TDS): Deducted monthly based on applicable tax slabs.")
    p.bullet("ESI: Applicable for salaries up to INR 21,000 per month.")
    p.h1("5. Loss of Pay (LOP)")
    p.body("Salary is deducted for unapproved leave, late joining, or suspension periods.")
    p.body("LOP calculation: (Monthly Gross Salary divided by Working Days in Month) multiplied by LOP Days.")
    p.h1("6. Salary Increments")
    p.bullet("Annual increments are effective from April 1 each year.")
    p.bullet("Increment percentage is linked to the annual performance rating.")
    p.trow("Performance Rating", "Increment Range", fill=True)
    p.trow("Outstanding (5)", "15% to 25%")
    p.trow("Exceeds Expectations (4)", "10% to 15%")
    p.trow("Meets Expectations (3)", "5% to 10%")
    p.trow("Needs Improvement (2)", "0% to 5%")
    p.trow("Unsatisfactory (1)", "No increment")
    p.h1("7. Full & Final Settlement")
    p.body("Upon resignation or termination, F&F settlement is processed within 45 working days, including salary up to last working day, encashment of unused annual leave, and recovery of any outstanding advances.")
    save(p, "hr", "Payroll_Policy.pdf")


def make_recruitment():
    p = Doc("Recruitment & Selection Policy")
    p.cover("Recruitment & Selection Policy",
            "End-to-End Hiring Process, Evaluation Criteria & Onboarding Standards",
            "Human Resources", "January 1, 2025", "v3.1",
            "Head of Talent Acquisition & CHRO")
    p.new()
    p.h1("1. Purpose")
    p.body("This policy defines TechCorp's approach to attracting, evaluating, and selecting qualified candidates. Our recruitment process is merit-based, transparent, and inclusive.")
    p.h1("2. Manpower Requisition")
    p.body("All recruitment starts with a Manpower Requisition Form (MRF) approved by the Department Head and HR Director. The MRF must include job title, grade, business justification, budget reference, and expected start date.")
    p.h1("3. Sourcing Channels")
    p.trow("Channel", "Usage", fill=True)
    p.trow("Internal Job Postings", "All positions posted internally for 5 days first")
    p.trow("Employee Referrals", "Eligible for referral bonus INR 25,000 to 50,000")
    p.trow("Job Portals", "LinkedIn, Naukri, Indeed")
    p.trow("Campus Recruitment", "Tier-1 and Tier-2 colleges")
    p.trow("Recruitment Agencies", "For senior and niche roles only")
    p.h1("4. Selection Process")
    p.h2("Stage 1: Resume Screening")
    p.body("HR screens resumes against the Job Description. Candidates not meeting minimum qualifications are rejected.")
    p.h2("Stage 2: HR Screening Call (20 to 30 minutes)")
    p.body("HR assesses cultural fit, communication skills, notice period, and salary expectations.")
    p.h2("Stage 3: Technical Assessment")
    p.body("Role-specific test — coding test, case study, or portfolio review. Minimum passing score is 70%.")
    p.h2("Stage 4: Technical Interview (1 to 2 rounds)")
    p.body("Panel assesses domain knowledge, problem-solving, and hands-on skills.")
    p.h2("Stage 5: Managerial Interview")
    p.body("Hiring manager evaluates leadership potential, ownership mindset, and team fit.")
    p.h2("Stage 6: HR Final Round")
    p.body("Covers behavioural competencies, career goals, and company values alignment.")
    p.h2("Stage 7: Background Verification")
    p.body("Employment history, education credentials, and criminal record check by a third-party agency.")
    p.h1("5. Offer & Onboarding")
    p.bullet("Offer letter issued within 3 working days of final approval.")
    p.bullet("Offer valid for 7 days; extension on written request only.")
    p.bullet("Pre-joining kit sent 2 weeks before start date.")
    p.bullet("Day 1 induction covers company overview, IT setup, HR policies, and team introduction.")
    p.bullet("Probation period: 6 months for all new hires.")
    p.h1("6. Diversity & Inclusion")
    p.body("TechCorp is an equal opportunity employer. All selection decisions are based solely on qualifications, skills, and merit. Discrimination on any basis is strictly prohibited.")
    save(p, "hr", "Recruitment_and_Selection_Policy.pdf")


def make_performance():
    p = Doc("Performance Review Policy")
    p.cover("Performance Review Policy",
            "Annual & Mid-Year Review Framework, Rating Scale & Feedback Process",
            "Human Resources & All Departments", "January 1, 2025", "v2.2",
            "CHRO & Management Committee")
    p.new()
    p.h1("1. Purpose")
    p.body("The Performance Review Process at TechCorp evaluates employee contributions, provides structured feedback, identifies development opportunities, and links performance to compensation decisions.")
    p.h1("2. Review Calendar")
    p.trow("Review Type", "Period", fill=True)
    p.trow("Annual Appraisal", "January 1 to December 31, reviewed in January")
    p.trow("Mid-Year Check-In", "July, informal and development-focused")
    p.trow("Probation Review", "End of month 3 and month 6 of employment")
    p.trow("PIP Review", "Monthly during a Performance Improvement Plan")
    p.h1("3. Performance Rating Scale")
    p.trow("Rating", "Label & Description", fill=True)
    p.trow("5 — Outstanding", "Consistently exceeds all goals; role model for team")
    p.trow("4 — Exceeds Expectations", "Frequently surpasses targets; shows leadership")
    p.trow("3 — Meets Expectations", "Achieves all goals; reliable and consistent")
    p.trow("2 — Needs Improvement", "Partially meets goals; requires development support")
    p.trow("1 — Unsatisfactory", "Fails to meet minimum requirements; PIP initiated")
    p.h1("4. Key Performance Areas (KPAs)")
    p.bullet("Goal Achievement: Delivery of agreed OKRs and KPIs. Weightage: 40%.")
    p.bullet("Quality of Work: Accuracy, innovation, and attention to detail. Weightage: 20%.")
    p.bullet("Collaboration and Teamwork: Cross-functional cooperation. Weightage: 15%.")
    p.bullet("Learning and Development: Upskilling and knowledge sharing. Weightage: 15%.")
    p.bullet("Leadership and Initiative: Ownership and proactive problem-solving. Weightage: 10%.")
    p.h1("5. Review Process")
    p.h2("Step 1: Employee Self-Assessment")
    p.body("Employee completes a self-assessment on HRMS, rating themselves on each KPA with evidence. Due: January 10.")
    p.h2("Step 2: Manager Assessment")
    p.body("Direct manager reviews the self-assessment and completes an independent rating. Due: January 20.")
    p.h2("Step 3: Calibration Session")
    p.body("Department heads and HR align ratings across teams for consistency. Due: January 25.")
    p.h2("Step 4: Feedback Conversation")
    p.body("Manager meets employee for a 1-on-1 discussion on strengths, areas of improvement, and career goals. Due: January 31.")
    p.h2("Step 5: Final Rating & Increment")
    p.body("HR Director approves final ratings. Salary increments communicated by March 15.")
    p.h1("6. Performance Improvement Plan (PIP)")
    p.body("Employees rated 1 or 2 consecutively for two review periods are placed on a PIP.")
    p.bullet("Duration: 60 to 90 days with clear, measurable goals.")
    p.bullet("Weekly progress reviews with manager and HR.")
    p.bullet("Successful completion: Employee returned to standard performance track.")
    p.bullet("Unsuccessful completion: Employment may be terminated.")
    save(p, "manager", "Performance_Review_Policy.pdf")


def make_promotion():
    p = Doc("Promotion Policy")
    p.cover("Promotion Policy",
            "Criteria, Evaluation Framework & Approval Process for Employee Promotions",
            "Human Resources & Senior Management", "January 1, 2025", "v2.0", "CHRO & CEO")
    p.new()
    p.h1("1. Purpose")
    p.body("This policy ensures that promotions at TechCorp are awarded based on merit, performance, and organisational need. It provides a transparent and consistent framework for career advancement.")
    p.h1("2. Types of Promotions")
    p.trow("Promotion Type", "Description", fill=True)
    p.trow("Annual Promotion", "Part of the annual appraisal cycle, effective April")
    p.trow("Merit Promotion", "Out-of-cycle for exceptional contribution")
    p.trow("Role-Based Promotion", "When employee takes on a higher-level role")
    p.trow("Fast Track Promotion", "For high performers meeting accelerated criteria")
    p.h1("3. Eligibility Criteria")
    p.body("To be considered for promotion, an employee must meet ALL of the following:")
    p.bullet("Minimum 18 months in current role (12 months for fast track).")
    p.bullet("Performance rating of 4 (Exceeds Expectations) or 5 (Outstanding) in the last annual review.")
    p.bullet("No active disciplinary action or PIP in the past 12 months.")
    p.bullet("Demonstrated readiness for next-level responsibilities.")
    p.bullet("Vacancy or business need at the higher grade.")
    p.h1("4. Evaluation Criteria")
    p.trow("Criterion", "Weightage", fill=True)
    p.trow("Performance Rating (last cycle)", "35%")
    p.trow("Skill and Competency Assessment", "25%")
    p.trow("Leadership and Ownership Demonstrated", "20%")
    p.trow("Peer and Stakeholder Feedback", "10%")
    p.trow("Learning and Development Activity", "10%")
    p.h1("5. Promotion Process")
    p.h2("Step 1: Nomination by Manager")
    p.body("Manager nominates employee via Promotion Recommendation Form on HRMS by December 15.")
    p.h2("Step 2: Department Head Review")
    p.body("Department head validates nominations and confirms business need and budget.")
    p.h2("Step 3: HR Assessment")
    p.body("HR validates eligibility, checks compliance, and benchmarks proposed grade against market data.")
    p.h2("Step 4: Promotion Committee Review")
    p.body("Cross-functional committee of senior leaders reviews shortlisted candidates. Panel interviews may be conducted for senior roles.")
    p.h2("Step 5: Approval and Communication")
    p.body("Final approval by CEO. Promoted employees notified by March 20. Promotion and revised offer letters issued by March 31.")
    p.h1("6. Salary Revision on Promotion")
    p.trow("Grade Jump", "Minimum Salary Increase", fill=True)
    p.trow("One Level (e.g., L3 to L4)", "15% to 25% increase")
    p.trow("Two Levels (e.g., L3 to L5)", "25% to 40% increase")
    p.trow("Individual Contributor to Manager", "30% to 45% increase")
    p.h1("7. Appeals Process")
    p.body("Employees who believe they were unfairly passed over may appeal within 15 days by submitting a written appeal to HR. Appeals are reviewed by the HR Director and a neutral senior leader.")
    save(p, "manager", "Promotion_Policy.pdf")


if __name__ == "__main__":
    print("Generating policy documents...")
    make_attendance()
    make_leave()
    make_conduct()
    make_wfh()
    make_payroll()
    make_recruitment()
    make_performance()
    make_promotion()
    print("\nAll 8 documents generated!")
    print("  employee/ — 4 documents")
    print("  hr/       — 2 documents")
    print("  manager/  — 2 documents")
